_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  asset_injector: 0
  auto_entitylabel: 0
  automated_cron: 0
  backup_migrate: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  coffee: 0
  color: 0
  colorbox: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_display: 0
  entity_reference_revisions: 0
  entity_reference_views_select: 0
  eva: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  geolocation: 0
  geolocation_google_maps: 0
  geolocation_leaflet: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_effects: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  layout_builder: 0
  layout_builder_styles: 0
  layout_discovery: 0
  link: 0
  map_component: 0
  markup: 0
  media: 0
  media_library: 0
  menu_ui: 0
  mmm_registration: 0
  mmm_tree_autofill: 0
  mysql: 0
  node: 0
  nun_helper: 0
  nun_maps: 0
  nun_migration: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pathauto: 0
  prepopulate: 0
  prlp: 0
  profile: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  responsive_image: 0
  rest: 0
  search: 0
  serialization: 0
  sharethis: 0
  shortcut: 0
  simple_fb_connect: 0
  sitemap: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  vardumper: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  bootstrap: 0
  nun: 0
  claro: 0
profile: standard
